FROM node:lts

WORKDIR /app

ENV AWS_REGION=eu-central-1
ENV AWS_ACCESS_KEY_ID=AKIAQ2FNHS7WQG3HPR5D
ENV AWS_SECRET_ACCESS_KEY=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
ENV JWTSECRET="CREATE A COMPLEX SECRET AND KEEP IT SAFE"
ENV SESSIONSECRET="SECRETS SHOULD KEEPS IN SAFE"
ENV HOST=https://comments-ws-1ff4be10b004.herokuapp.com
ENV PORTCLIENT=5173
ENV VITE_HOST=https://comments-ws-1ff4be10b004.herokuapp.com

COPY package*.json ./

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000 80 443 

CMD ["npm", "run", "start"]